---
- hosts: girls
  vars:
    http_port: 80
    max_clients: 200
    remote_user: ec2-user
  tasks:
  - name: install docker
    yum: name=docker state=latest
    become: yes
    become_method: sudo

  - name: install docker-compose
    pip: name=docker-compose
    become: yes
    become_method: sudo

  - name: create usergroup docker
    command: groupadd docker
    become: yes
    become_method: sudo
    ignore_errors: yes

  - name: add ec2-user to docker group
    command: usermod -a -G docker ec2-user
    become: yes
    become_method: sudo

  - name: start docker service
    service: name=docker state=started
    become: yes
    become_method: sudo

  - name: create data directory
    file: path=/data state=directory owner=ec2-user group=ec2-user mode=0755
    become: yes
    become_method: sudo

  - name: create jenkins_home directory
    file: path=/var/jenkins_home state=directory owner=ec2-user group=ec2-user mode=0777
    become: yes
    become_method: sudo

  - name: create sonarqube-db directory
    file: path=/var/sonarqube-db state=directory owner=ec2-user group=ec2-user mode=0777
    become: yes
    become_method: sudo

  - name: copy docker-compose script
    copy: src=docker-compose.yml dest=/data/docker-compose.yml owner=ec2-user group=ec2-user mode=0777
    become: yes
    become_method: sudo

  - name: copy configuration for Jenkins docker image
    copy: src=girlsday-jenkins dest=/data owner=ec2-user group=ec2-user mode=0777
    become: yes
    become_method: sudo

  - name: create Jenkins docker image
    command: docker build -t girlsday-jenkins .
    args:
      chdir: /data/girlsday-jenkins

  - name: run docker-compose
    command: docker-compose up
    args:
      chdir: /data
